#!/usr/bin/python

import dns.resolver

NameServers = raw_input("Which nameservers to you wish to question? >> ")
DomainNameToSearch = raw_input("Enter Domain to search >> ")
RecordType = raw_input("Enter Record Type >> ")
myResolver = dns.resolver.Resolver()
#myResolver.nameservers = ['8.8.8.8', '8.8.4.4']
myResolver.nameservers = [NameServers]

try:
        myAnswers = myResolver.query(DomainNameToSearch, RecordType)
        for rdata in myAnswers:
                print rdata
except Exception as e:
        print e
